services:
  riverpark:
    build:
      context: .
    container_name: iso-riverpark-web
    ports:
      - "5175:80"
    restart: unless-stopped
    networks:
      - nginx-proxy-manager

networks:
  nginx-proxy-manager:
    external: true
    name: ${NPM_NETWORK:-nginx-proxy-manager}
