services:
  riverpark:
    build:
      context: .
    container_name: iso-riverpark-web
    ports:
      - "5175:80"
    restart: unless-stopped
    networks:
      - vantive-net

networks:
  vantive-net:
    external: true
    name: ${NPM_NETWORK:-vantive-api_vantive-net}
